---
version: '2.0'
services:
  packer_build:
    image: hashicorp/packer:latest
    volumes:
      - "$HOME/.aws:/root/.aws"
      - ".:/build"
    working_dir: /build
    environment:
      AWS_DEFAULT_REGION: ap-southeast-2
      BASE_AMI_ID:
      APP_NAME:
      AWS_PROFILE:
      BUILD_IAM_PROFILE:

  ami_clean:
    image: jagregory/amicleaner
    environment:
      AWS_DEFAULT_REGION: ap-southeast-2
      AWS_PROFILE:
    volumes:
      - "$HOME/.aws:/root/.aws"

  stackup:
    image: realestate/stackup:latest
    volumes:
      - "$HOME/.aws:/root/.aws"
      - ".:/build"
    working_dir: /app
    environment:
      AWS_DEFAULT_REGION: ap-southeast-2
      AWS_PROFILE:

  awscli:
    build:
      context: .
      dockerfile: Dockerfile.awscli
    volumes:
      - "$HOME/.aws:/root/.aws"
      - ".:/build"
    environment:
      AWS_DEFAULT_REGION: ap-southeast-2
      AWS_PROFILE:
